<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_StudentTeacherConsultant</name>
   <tag></tag>
   <elementGuidId>4e97e69e-10e3-46bc-b39f-cb2778fd623e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']/div[5]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d46cc782-0b38-4c48-bdc6-ead3511faff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>114d3922-b711-4907-8db6-010930621a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style</name>
      <type>Main</type>
      <value>btn-info</value>
      <webElementGuid>0447e2f5-fe06-40f0-baba-7012f660839b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Student
										Teacher
										Consultant
									</value>
      <webElementGuid>093a79bc-a037-4aea-8ca0-d5cd69f50e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>c5b30a3d-ce9d-42ae-9b54-3421d10130c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[5]/select</value>
      <webElementGuid>c75e9519-c830-495a-b519-5f505fbe6af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::select[1]</value>
      <webElementGuid>92916c7f-5223-4a87-aa1e-860961f3d789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::select[1]</value>
      <webElementGuid>7f82cd47-8bc0-4598-aee0-d932e1a69f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rahulshettyacademy'])[1]/preceding::select[1]</value>
      <webElementGuid>4c503957-1b1d-4df2-a630-df91673e0f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5ca7e6e3-e711-4623-9220-38af9016506d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
										Student
										Teacher
										Consultant
									' or . = '
										Student
										Teacher
										Consultant
									')]</value>
      <webElementGuid>7e55ac9c-54d0-4530-ae08-449e5913f6df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
