<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RahulShetty</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>80df610c-193a-4fad-90fc-0501ac4a3ea7</testSuiteGuid>
   <testCaseLink>
      <guid>b1fcb9d1-c33a-4b46-8b6c-c575914b9c4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RahulShettyTestCase/RahulShettyLoginPage</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9c011541-43be-4b24-a968-a37ecdb7dd3b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/RahulShettyData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9c011541-43be-4b24-a968-a37ecdb7dd3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>a031c246-0d3f-40c6-a5de-ffcfe9d17308</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9c011541-43be-4b24-a968-a37ecdb7dd3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>7ef3d49b-ab2e-4f86-a178-322f92f92ff6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9c011541-43be-4b24-a968-a37ecdb7dd3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c43dd5aa-e5fd-420f-9b7f-3b85955c6adf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97742ad4-a34a-40ca-9e20-c4a2ae7a211b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fa9b038-030f-4267-bf78-48c0c52ba97d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31ae69c4-3e84-4e83-8107-48825000e8b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bb732e2-c6e8-4a61-af12-4270071a8c98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>985d9aa5-7929-4853-bbb2-a643606c8608</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9763c220-d19a-449e-a3e5-d00b7447d616</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>210a47d4-0b02-4080-8e51-f5274aed4ccf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38950928-f2ca-4ae6-b5ec-694699d470b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a95b3d1b-95d4-4cdf-b0cc-4c3defe0463a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf458b02-46ba-46b9-8803-5fddd50d265e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a2426a1-d81b-4252-a553-76039686c59d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cebcdb8-ca9a-4ec3-9602-2c9c6d9fe2e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f940c918-9a87-43cd-89c2-9a806500e416</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
